// <auto-generated />
using GroupAPIFinal.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GroupAPIFinal.Migrations
{
    [DbContext(typeof(FullContext))]
    [Migration("20230426021158_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GroupAPIFinal.Models.UserFoods", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("FavCuisine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FavFruit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FavMeal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FavMeat")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Foods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FavCuisine = "Korean",
                            FavFruit = "Apple",
                            FavMeal = "Lunch",
                            FavMeat = "Chicken"
                        },
                        new
                        {
                            Id = 2,
                            FavCuisine = "German",
                            FavFruit = "Banana",
                            FavMeal = "Dinner",
                            FavMeat = "Steak"
                        },
                        new
                        {
                            Id = 3,
                            FavCuisine = "American",
                            FavFruit = "Grape",
                            FavMeal = "Dinner",
                            FavMeat = "Salmon"
                        });
                });

            modelBuilder.Entity("GroupAPIFinal.Models.UserHobbies", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Hobby1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hobby2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hobby3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hobby4")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Hobbies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Hobby1 = "Painting",
                            Hobby2 = "Drawing",
                            Hobby3 = "Photography",
                            Hobby4 = "Knitting"
                        },
                        new
                        {
                            Id = 2,
                            Hobby1 = "Video Games",
                            Hobby2 = "Shopping",
                            Hobby3 = "Hiking",
                            Hobby4 = "Writing"
                        },
                        new
                        {
                            Id = 3,
                            Hobby1 = "Traveling",
                            Hobby2 = "Biking",
                            Hobby3 = "Golfing",
                            Hobby4 = "Movie Watching"
                        });
                });

            modelBuilder.Entity("GroupAPIFinal.Models.UserInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Birthdate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Major")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UserInfo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Birthdate = "June 3rd 2003",
                            Major = "Information Technology",
                            Name = "Drew Rawlins",
                            year = 2025
                        },
                        new
                        {
                            Id = 2,
                            Birthdate = "January 12th 2002",
                            Major = "Information Technology",
                            Name = "Jacob Collier",
                            year = 2025
                        },
                        new
                        {
                            Id = 3,
                            Birthdate = "January 22nd 2003",
                            Major = "Information Technology",
                            Name = "Dylan Mullarkey",
                            year = 2025
                        });
                });

            modelBuilder.Entity("GroupAPIFinal.Models.UserLocationInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AreaCode")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ZipCode")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UserLocation");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AreaCode = 513,
                            City = "Cincinnati",
                            State = "Ohio",
                            ZipCode = 45244
                        },
                        new
                        {
                            Id = 2,
                            AreaCode = 513,
                            City = "Milford",
                            State = "Ohio",
                            ZipCode = 45150
                        },
                        new
                        {
                            Id = 3,
                            AreaCode = 614,
                            City = "Columbus",
                            State = "Ohio",
                            ZipCode = 43004
                        });
                });

            modelBuilder.Entity("GroupAPIFinal.Models.UserMusic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("FavArtist")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FavBand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FavGenre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FavSong")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Music");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FavArtist = "Elvis Pressley",
                            FavBand = "The Beatles",
                            FavGenre = "Classic",
                            FavSong = "Here Comes The Sun"
                        },
                        new
                        {
                            Id = 2,
                            FavArtist = "Micheal Jackson",
                            FavBand = "Dave Matthews Band",
                            FavGenre = "Pop",
                            FavSong = "Billie Jean"
                        },
                        new
                        {
                            Id = 3,
                            FavArtist = "George Strait",
                            FavBand = "AC/DC",
                            FavGenre = "Country",
                            FavSong = "Troubadour"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
